[package]
name = "pdx-bes-memo"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Jason Law"]
license = "MIT"
description = "A Typst template for City of Portland Bureau of Environmental Services Memos - based on the official Word template"
